### PR TITLE
Do not merge before 2nd August!! Updated bx cr plan-upgrade command

### PR DESCRIPTION
**Pull request by Nadine2016**
This PR must not be merged before July 27th, 2017. Thanks

removal of legacy plan information

### CODE REVIEW

**Comment by SueGraham** [comment]
@sefuhrer Postponed from 27th July - please do not action until 3rd August - thanks

**Comment by SueGraham** [comment]
@sefuhrer @kKronstainBrown This is good to go today - Wednesday 2nd August. Please can you push to prod.

**Comment by sefuhrer** [comment]
Merged per Sue's request.

**Comment by SueGraham** [comment]
@sefuhrer Thanks :)

**Comment by SueGraham** [comment]
@sefuhrer Thanks :)

**Pull request merged**
